/**
 * Generates IMAGE-BRIEF.md: every route, what the page argues, and what its
 * hero image needs to show.
 *
 * Written as a generator rather than a hand-kept document because the route
 * list comes from the data files. Add an industry and it appears here; the
 * brief cannot drift from the site.
 *
 *   node scripts/image-brief.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";

/** Pull `field: "value"` pairs out of a data file without importing TS. */
function records(file, keys) {
  const src = readFileSync(file, "utf8");
  const out = [];
  const slugRe = /slug: "([^"]+)"/g;
  let m;
  const positions = [];
  while ((m = slugRe.exec(src))) positions.push({ slug: m[1], at: m.index });
  positions.forEach((p, i) => {
    const body = src.slice(p.at, positions[i + 1]?.at ?? src.length);
    const rec = { slug: p.slug };
    for (const k of keys) {
      // Quoted strings and template literals both appear in these files --
      // `image: \`${DIR}/x.webp\`` is the second kind, and missing it made
      // the brief claim ten industries had no photograph when they do.
      const q = new RegExp(`${k}:\\s*\\n?\\s*"((?:[^"\\\\]|\\\\.)*)"`).exec(body);
      const t = new RegExp(`${k}:\\s*\\n?\\s*\\\`([^\\\`]*)\\\``).exec(body);
      if (q) rec[k] = q[1].replace(/\\"/g, '"');
      else if (t) rec[k] = t[1];
    }
    out.push(rec);
  });
  return out.filter((r) => !/^\$\{/.test(r.slug));
}

const services = records("src/data/services.ts", ["title", "short"]);
const industries = records("src/data/industries.ts", ["name", "line", "image"]);
const cases = records("src/data/caseStudies.ts", ["title", "category", "problem"]);
const products = records("src/data/products.ts", ["name", "tagline", "category"]);
const blogs = records("src/data/blogs.ts", ["title", "category", "excerpt"]);

const trim = (s, n = 155) => {
  if (!s) return "";
  const t = s.replace(/\s+/g, " ").trim();
  return t.length > n ? t.slice(0, n - 1).replace(/[ ,.;:]$/, "") + "…" : t;
};

const L = [];
const p = (s = "") => L.push(s);

p("# Image brief, route by route");
p();
p("Generated by `node scripts/image-brief.mjs`. Do not hand-edit: add a service,");
p("industry, case study, product or article and re-run it.");
p();
p("## What each image is for");
p();
p("Every page carries a card in the **top right of its hero**, the slot the");
p("looping video occupies on the home page. It is the first thing beside the");
p("headline, so it should show the *subject of the page*, not the company.");
p();
p("**House style, so the set holds together:**");
p();
p("- **Line art or technical drawing**, not photography and not 3D renders, except");
p("  for the industry pages where a real photograph of the setting works better.");
p("- **Landscape 4:3** for hero cards (the home video is 3:4 because it sits beside");
p("  a three-line headline; everything else is wider).");
p("- **A subject, not a metaphor.** A drone over a crop row beats a glowing brain.");
p("- **No invented UI.** If it looks like a screenshot of a product, it will be read");
p("  as one. Diagrams and drawings are safe; fake dashboards are not.");
p("- **No vendor logos**, no recognisable faces, no client names.");
p("- Works on a warm graphite `#262621` ground and a stone `#E3E1D8` one. A drawing");
p("  on a transparent or near-white background needs a dark twin, or it glares.");
p();
p("Drop files into `public/images/<section>/<slug>.webp` and tell me; I will wire");
p("them up and generate the dark variants where they are needed.");
p();
p("---");
p();

function table(title, rows, note) {
  p(`## ${title}`);
  p();
  if (note) { p(note); p(); }
  p("| Route | What the page argues | What the image should show |");
  p("|---|---|---|");
  for (const r of rows) p(`| \`${r.route}\` | ${r.what} | ${r.image} |`);
  p();
}

table("Top level", [
  { route: "/", what: "AI systems that survive real users, load and handover", image: "**Done.** The looping plexus video, top right of the hero." },
  { route: "/about", what: "Who builds it, how, and where we are", image: "**Done.** Founder line art on a paper plate." },
  { route: "/services", what: `${services.length} capabilities in four groups`, image: "A drawn capability map: four clusters, lines between the ones that ship together." },
  { route: "/industries", what: `${industries.length} domains, and what shapes the system in each`, image: "A drawn grid of domain glyphs — a field, a ward, a warehouse, a call centre — one line weight throughout." },
  { route: "/case-studies", what: `${cases.length} production systems, problem to outcome`, image: "A drawn timeline: brief, build, handover, with the artifacts hanging off it." },
  { route: "/products", what: `${products.length} products we build and run ourselves`, image: "A drawn shelf of device outlines, screens blank. Real screenshots already sit in the cards below." },
  { route: "/blogs", what: "Field notes from the work", image: "A drawn desk: notebook, terminal window, coffee. Nothing branded." },
  { route: "/contact", what: "Send a brief, get an engineer's reply", image: "A drawn envelope and a calendar, or the two offices as a simple map." },
  { route: "/book", what: "Thirty minutes, no deck", image: "A drawn clock and calendar grid with one slot marked." },
  { route: "/careers", what: "How we hire, and what is open", image: "A drawn pair-programming scene: two chairs, one screen, whiteboard behind." },
]);

table("Capabilities", services.map((s) => ({
  route: `/services/${s.slug}`,
  what: trim(s.short || s.title),
  image: `Line art of the mechanism, not the benefit. Ask: what would you draw on a whiteboard explaining “${trim(s.title, 60)}” to an engineer?`,
})), `${services.length} routes. \`sovereign-ai\` already has a drawn boundary diagram in its hero.`);

table("Industries", industries.map((i) => ({
  route: `/industries/${i.slug}`,
  what: trim(i.line),
  image: i.image
    ? "**Has an image.** Replace only if a better one turns up."
    : "A photograph of the setting works better here than a drawing. Currently rendering a drawn pipeline as the stand-in.",
})), `${industries.length} routes. These are the pages where real photography beats illustration.`);

table("Case studies", cases.map((c) => ({
  route: `/case-studies/${c.slug}`,
  what: trim(c.problem || c.title),
  image: "**Drawn pipeline already in place.** These are under NDA, so nothing that could read as a screenshot of the client's system.",
})), `${cases.length} routes.`);

table("Products", products.map((pr) => ({
  route: `/products/${pr.slug}`,
  what: trim(pr.tagline || pr.name),
  image: "**Real screenshots already in place.** Only needed if you want a drawn cover as well.",
})), `${products.length} routes.`);

table("Articles", blogs.map((b) => ({
  route: `/blogs/${b.slug}`,
  what: trim(b.excerpt || b.title),
  image: "One drawn concept from the article. Currently reusing a shared illustration set.",
})), `${blogs.length} routes.`);

p("---");
p();
p("## Priority, if you are making these by hand");
p();
p("1. **Industry pages without a photograph** — the widest visible gap, and the");
p("   pages a buyer lands on from search.");
p("2. **The ten top-level routes** — most traffic, and they set the house style.");
p("3. **Capability pages**, starting with the four that open most engagements:");
p("   generative-ai, agentic-ai, rag-enterprise-search, voice-ai.");
p("4. Articles and product covers last; both already render something reasonable.");
p();

writeFileSync("IMAGE-BRIEF.md", L.join("\n"));
console.log(`IMAGE-BRIEF.md written: ${services.length + industries.length + cases.length + products.length + blogs.length + 10} routes`);
